# Generated by `mix metacredo.gen.config`.
# Move any check to the `disabled` list or set its second element to `false`
# to turn it off.  Add `{ModuleName, [param: value]}` to customise params.
%{
  configs: [
    %{
      name: "default",
      files: %{
        included: ["lib/", "src/", "web/"],
        excluded: [
          ~r"/_build/",
          ~r"/deps/",
          ~r"/node_modules/"
        ]
      },
      checks: %{
        enabled: [
              # -- Consistency --
              {MetaCredo.Check.Consistency.ExceptionNames, []},
              {MetaCredo.Check.Consistency.ParameterPatternMatching, []},
              # -- Design --
              {MetaCredo.Check.Design.HighComplexity, []},
              {MetaCredo.Check.Design.HighCoupling, []},
              {MetaCredo.Check.Design.LowCohesion, []},
              {MetaCredo.Check.Design.TagFixme, []},
              {MetaCredo.Check.Design.TagTodo, []},
              # -- Observability --
              {MetaCredo.Check.Observability.MissingTelemetryForExternalHttp, []},
              {MetaCredo.Check.Observability.MissingTelemetryInAuthPlug, []},
              {MetaCredo.Check.Observability.MissingTelemetryInLiveviewMount, []},
              {MetaCredo.Check.Observability.MissingTelemetryInObanWorker, []},
              {MetaCredo.Check.Observability.TelemetryInRecursiveFunction, []},
              # -- Readability --
              {MetaCredo.Check.Readability.ComplexConditional, []},
              {MetaCredo.Check.Readability.DeepNesting, []},
              {MetaCredo.Check.Readability.FunctionNames, []},
              {MetaCredo.Check.Readability.LargeNumbers, []},
              {MetaCredo.Check.Readability.LongFunction, []},
              {MetaCredo.Check.Readability.LongParameterList, []},
              {MetaCredo.Check.Readability.MagicNumber, []},
              {MetaCredo.Check.Readability.ModuleNames, []},
              {MetaCredo.Check.Readability.NestedFunctionCalls, []},
              {MetaCredo.Check.Readability.SinglePipe, []},
              {MetaCredo.Check.Readability.Specs, []},
              {MetaCredo.Check.Readability.VariableNames, []},
              # -- Refactor --
              {MetaCredo.Check.Refactor.AppendSingleItem, []},
              {MetaCredo.Check.Refactor.CodeDuplication, []},
              {MetaCredo.Check.Refactor.DeadCode, []},
              {MetaCredo.Check.Refactor.DoubleBooleanNegation, []},
              {MetaCredo.Check.Refactor.FilterCount, []},
              {MetaCredo.Check.Refactor.NegatedConditionWithElse, []},
              {MetaCredo.Check.Refactor.PipeChainStart, []},
              {MetaCredo.Check.Refactor.SimplifyConditional, []},
              {MetaCredo.Check.Refactor.UnlessWithElse, []},
              {MetaCredo.Check.Refactor.VariableRebinding, []},
              # -- Security --
              {MetaCredo.Check.Security.HardcodedValue, []},
              {MetaCredo.Check.Security.ImproperInputValidation, []},
              {MetaCredo.Check.Security.IncorrectAuthorization, []},
              {MetaCredo.Check.Security.InlineJavascript, []},
              {MetaCredo.Check.Security.InsecureDirectObjectReference, []},
              {MetaCredo.Check.Security.MissingAuthentication, []},
              {MetaCredo.Check.Security.MissingAuthorization, []},
              {MetaCredo.Check.Security.MissingCSRFProtection, []},
              {MetaCredo.Check.Security.PathTraversal, []},
              {MetaCredo.Check.Security.SQLInjection, []},
              {MetaCredo.Check.Security.SSRFVulnerability, []},
              {MetaCredo.Check.Security.SensitiveDataExposure, []},
              {MetaCredo.Check.Security.TOCTOU, []},
              {MetaCredo.Check.Security.UnrestrictedFileUpload, []},
              {MetaCredo.Check.Security.XSSVulnerability, []},
              # -- Warning --
              {MetaCredo.Check.Warning.BlockingInPlug, []},
              {MetaCredo.Check.Warning.BoolOperationOnSameValues, []},
              {MetaCredo.Check.Warning.CallbackHell, []},
              {MetaCredo.Check.Warning.DebugLeftover, []},
              {MetaCredo.Check.Warning.DirectStructUpdate, []},
              {MetaCredo.Check.Warning.ImperativeStatusHandling, []},
              {MetaCredo.Check.Warning.InefficientFilter, []},
              {MetaCredo.Check.Warning.LazyLogging, []},
              {MetaCredo.Check.Warning.MissingErrorHandling, []},
              {MetaCredo.Check.Warning.MissingHandleAsync, []},
              {MetaCredo.Check.Warning.MissingPreload, []},
              {MetaCredo.Check.Warning.MissingThrottle, []},
              {MetaCredo.Check.Warning.NPlusOneQuery, []},
              {MetaCredo.Check.Warning.OperationOnSameValues, []},
              {MetaCredo.Check.Warning.OperationWithConstantResult, []},
              {MetaCredo.Check.Warning.RaiseInsideRescue, []},
              {MetaCredo.Check.Warning.SilentErrorCase, []},
              {MetaCredo.Check.Warning.SwallowingException, []},
              {MetaCredo.Check.Warning.SyncOverAsync, []},
              {MetaCredo.Check.Warning.UnmanagedTask, []},
              {MetaCredo.Check.Warning.UnsafeExec, []},
              {MetaCredo.Check.Warning.UnusedOperation, []}
        ],
        disabled: [
              {MetaCredo.Check.Readability.ModuleDoc, []}
        ]
      }
    }
  ]
}
