defmodule Mix.Tasks.Metacredo.Gen.Config do
  @shortdoc "Generate a default .metacredo.exs configuration file"
  @moduledoc """
  Generates a `.metacredo.exs` configuration file in the current directory.

  The generated file lists every available MetaCredo check grouped by category.
  To disable a check, move its entry to the `disabled` list or set its second
  element to `false`:

      {MetaCredo.Check.Security.SQLInjection, false}

  ## Example Output

      %{
        configs: [
          %{
            name: "default",
            files: %{
              included: ["lib/", "src/", "web/"],
              excluded: [~r"/_build/", ~r"/deps/", ~r"/node_modules/"]
            },
            checks: %{
              enabled: [
                # -- Consistency --
                {MetaCredo.Check.Consistency.ExceptionNames, []},
                ...
              ],
              disabled: []
            }
          }
        ]
      }

  ## Usage

      $ mix metacredo.gen.config

  ## Options

    * `--force` - Overwrite an existing `.metacredo.exs`
    * `--global` - Generate the configuration file in the user's global config directory (e.g. `~/.config/metacredo/.metacredo.exs`)
  """

  use Mix.Task

  @impl Mix.Task
  def run(argv) do
    force? = "--force" in argv
    global? = "--global" in argv

    path =
      if global? do
        MetaCredo.Config.global_config_path()
      else
        MetaCredo.Config.default_config_path()
      end

    if File.exists?(path) and not force? do
      Mix.shell().info("#{path} already exists. Use --force to overwrite.")
    else
      Mix.Task.run("app.start", [])
      File.mkdir_p!(Path.dirname(path))
      File.write!(path, build_config())
      Mix.shell().info("Created #{path}")
    end
  end

  # -- Private --

  defp build_config do
    disabled_mods = MetaCredo.Config.default_disabled_checks()
    all_discovered = discover_checks()

    {disabled_checks, enabled_checks} =
      Enum.split_with(all_discovered, &(&1 in disabled_mods))

    enabled_section = format_checks_section(enabled_checks)
    disabled_section = format_checks_section(disabled_checks)

    """
    # Generated by `mix metacredo.gen.config`.
    # Move any check to the `disabled` list or set its second element to `false`
    # to turn it off.  Add `{ModuleName, [param: value]}` to customise params.
    %{
      configs: [
        %{
          name: "default",
          no_db: false,
          no_user: false,
          files: %{
            included: ["lib/", "src/", "web/"],
            excluded: [
              ~r"/_build/",
              ~r"/deps/",
              ~r"/node_modules/"
            ]
          },
          checks: %{
            enabled: [
    #{enabled_section}
            ],
            disabled: [
    #{disabled_section}
            ]
          }
        }
      ]
    }
    """
  end

  defp format_checks_section([]), do: ""

  defp format_checks_section(checks) do
    checks
    |> Enum.group_by(& &1.category())
    |> Enum.sort_by(fn {cat, _} -> to_string(cat) end)
    |> Enum.map_join(",\n", fn {category, category_checks} ->
      header = "              # -- #{format_category(category)} --"

      lines =
        category_checks
        |> Enum.sort_by(&inspect/1)
        |> Enum.map_join(",\n", fn mod ->
          "              {#{inspect(mod)}, []}"
        end)

      header <> "\n" <> lines
    end)
  end

  defp discover_checks do
    modules =
      case :application.get_key(:metacredo, :modules) do
        {:ok, mods} when mods != [] -> mods
        _ -> discover_loaded_modules()
      end

    Enum.filter(modules, fn mod ->
      Code.ensure_loaded?(mod) and
        String.starts_with?(to_string(mod), "Elixir.MetaCredo.Check.") and
        function_exported?(mod, :run, 2) and
        function_exported?(mod, :category, 0)
    end)
  end

  defp discover_loaded_modules do
    :code.all_loaded()
    |> Enum.map(fn {mod, _} -> mod end)
    |> Enum.filter(&(to_string(&1) |> String.starts_with?("Elixir.MetaCredo.Check.")))
  end

  defp format_category(category) do
    category
    |> to_string()
    |> String.replace("_", " ")
    |> String.split()
    |> Enum.map_join(" ", &String.capitalize/1)
  end
end
